import { Geist, Geist_Mono,  Montserrat, Roboto  } from "next/font/google";
import "@fortawesome/fontawesome-free/css/all.min.css"
import "bootstrap-icons/font/bootstrap-icons.min.css"
import "../styles/animate.min.css"
import "bootstrap/dist/css/bootstrap.min.css"
import "./globals.css";
import "remixicon/fonts/remixicon.css"
import Header from "@/component/Header";
import Footer from "@/component/Footer";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["500", "700"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={` ${roboto.variable}  ${montserrat.variable} `}>
      <script   src="https://www.google.com/recaptcha/api.js"  async  defer></script>
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
